### ISSUE TITLE
tradurre italiano in inglese e localizzare correttamente

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniCMS#7]
https://github.com/UniversitaDellaCalabria/uniCMS/blob/a6ead29c2480c47e180f0d946cd560503e37cc53/src/cms/contexts/views.py#L90

**Comment by francesco-filicetti** [comment]
done.
thank you

**Comment by peppelinux** [comment]
Closed via https://github.com/UniversitaDellaCalabria/uniCMS/pull/8
